apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amel
resources:
  - namespace.yaml
  - configmap.yaml
  - feast-server.yaml
  - inference-api.yaml
  - source-simulator.yaml
  - stream-ingestor.yaml
  - ingress.yaml
